# Generated by Django 3.2.6 on 2021-08-05 12:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=20)),
                ('address', models.TextField()),
            ],
            managers=[
                ('abc', django.db.models.manager.Manager()),
            ],
        ),
    ]
