# Generated by Django 3.2.5 on 2021-08-05 15:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('manager_mod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
            managers=[
                ('morelation', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='A',
        ),
    ]
